export interface Project {
  id: string;
  name: string;
  type: string | null;
  portfolio: string | null;
  sponsor: string | null;
  health: string | null;
  pct_complete: number;
  priority: string | null;
  start_date: string | null;
  end_date: string | null;
  actual_end: string | null;
  functional_spec_due: string | null;
  functional_spec_completed: string | null;
  technical_spec_due: string | null;
  technical_spec_completed: string | null;
  team: string | null;
  pm: string | null;
  ba: string | null;
  functional_lead: string | null;
  technical_lead: string | null;
  developer_lead: string | null;
  tshirt_size: string | null;
  est_hours: number;
  est_cost: number | null;
  budget: number;
  actual_cost: number;
  forecast_cost: number;
  role_allocations: Record<string, number>;
  notes: string | null;
  sort_order: number | null;
  initiative_id: string | null;
  initiative_name: string | null;
  planned_it_start: string | null;
  is_active: boolean;
  duration_weeks: number | null;
}
